const ftaTypeLinks: {[key: string]: string[]} = {
    'alienDeployments.battleScript': ['battleScripts'], // FtA
    'battleScripts.commands[].unitSet': ['units'], // FtA part
    'covertOperations.successEvent': ['events'],
    'covertOperations.failureEvent': ['events'],
    'covertOperations.progressEvent': ['events'],
    'covertOperations.successWeightedItemList': ['items'], // untested
    'covertOperations.failureWeightedItemList': ['items'], // untested
    'covertOperations.successResearchList': ['research'],
    'covertOperations.failureResearchList': ['research'],
    'covertOperations.successMissions': ['alienMissions'], // untested
    'covertOperations.failureMissions': ['alienMissions'], // untested
    'covertOperations.instantTrapDeployment': ['alienDeployments'],
    'covertOperations.instantSuccessDeployment': ['alienDeployments'],
    'covertOperations.successReputationScore ': ['diplomacyFactions'],
    'covertOperations.failureReputationScore ': ['diplomacyFactions'],
    'covertOperations.requires': ['research'],
    'covertOperations.requiresBaseFunc': ['facilities.provideBaseFunc'],
    'covertOperations.requiredItems': ['items'],
    'covertOperations.allowedArmor': ['armors'],
    'covertOperations.soldierTypeEffectiveness': ['soldiers'], // untested
    '/^events\\.customAnswers\\.[0-3]\\.title$/': ['events'], // untested
    'diplomacyFactions.discoverResearch': ['research'],
    'diplomacyFactions.discoverEvent': ['events'],
    'diplomacyFactions.helpTreatyMissions': ['missionScripts'],
    'diplomacyFactions.helpTreatyEvents': ['eventScripts'],
    // sellingSet - this is changing ATM by Stoddard dramatically
    'units.altRecoveredUnit': ['units']
};

export const typeLinks: {[key: string]: string[]} = Object.assign(ftaTypeLinks, {
    'alienDeployments.abortCutscene': ['cutscenes'],
    '/^alienDeployments\\.alienBaseUpgrades\\.\\d+$/': ['alienDeployments'],
    'alienDeployments.briefing.cutscene': ['cutscenes'],
    'alienDeployments.briefing.music': ['musics'],
    'alienDeployments.civiliansByType': ['units'],
    'alienDeployments.customUfo': ['ufos'],
    'alienDeployments.data[].extraRandomItems[]': ['items'],
    'alienDeployments.data[].itemSets[]': ['items'],
    'alienDeployments.enviroEffects': ['enviroEffects'],
    'alienDeployments.loseCutscene': ['cutscenes'],
    'alienDeployments.missionBountyItem': ['items'],
    'alienDeployments.nextStage': ['alienDeployments'],
    'alienDeployments.race': ['alienRaces'],
    'alienDeployments.randomRace': ['alienRaces'],
    'alienDeployments.script': ['mapScripts'],
    'alienDeployments.startingCondition': ['startingConditions'],
    'alienDeployments.terrains': ['terrains'],
    'alienDeployments.unlockedResearch': ['research'],
    'alienDeployments.winCutscene': ['cutscenes'],
    'alienRaces.baseCustomDeploy': ['alienDeployments'],
    'alienRaces.baseCustomMission': ['alienDeployments'],
    'alienRaces.members': ['units'],
    'alienRaces.membersRandom[]': ['units'],
    'alienRaces.retaliationMission': ['alienMissions'],
    'armors.builtInWeapons': ['items'],
    'armors.corpseBattle': ['items'],
    'armors.corpseGeo': ['items'],
    'armors.requires': ['research'],
    'armors.specialWeapon': ['items'],
    'armors.storeItem': ['items'],
    'armors.tags': ['extended.tags.RuleArmor'],
    'armors.units': ['soldiers'],
    'crafts.refuelItem': ['items'],
    'crafts.requires': ['research'],
    'crafts.weaponStrings': ['craftWeapons.weaponType'], // (is this just a translatable?)
    'facilities.buildCostItems': ['items'],
    'facilities.buildOverFacilities': ['facilities'],
    'facilities.destroyedFacility': ['facilities'],
    'facilities.mapName': ['terrains.mapBlocks[]'],
    'facilities.requires': ['research'],
    'itemCategories.replaceBy': ['itemCategories'],
    '/^items\\.ammo\\.[0-3]\\.compatibleAmmo$/': ['items'],
    'items.categories': ['itemCategories'],
    'items.defaultInventorySlot': ['invs'],
    'items.requires': ['research'],
    'items.requiresBuy': ['research'],
    'items.requiresBuyBaseFunc': ['facilities.provideBaseFunc'],
    'items.spawnUnit': ['units'],
    'items.supportedInventorySections': ['invs'],
    'items.tags': ['extended.tags.RuleItem'],
    'items.zombieUnit': ['units'],
    'items.zombieUnitByArmorFemale.key': ['armors'],
    'items.zombieUnitByArmorFemale.value': ['units'],
    'items.zombieUnitByArmorMale.key': ['armors'],
    'items.zombieUnitByArmorMale.value': ['units'],
    'items.zombieUnitByType.key': ['units'],
    'items.zombieUnitByType.value': ['units'],
    'mapScripts.commands[].craftName': ['crafts'],
    'mapScripts.commands[].randomTerrain': ['terrains'],
    'mapScripts.commands[].terrain': ['terrains'],
    'mapScripts.commands[].UFOName': ['ufos'],
    'mapScripts.commands[].verticalLevels[].terrain': ['terrains'],
    'research.lookup': ['research'],
    'research.cutscene': ['cutscenes'],
    'research.spawnedItem': ['items'],
    'research.spawnedEvent': ['events'],
    'research.dependencies': ['research'],
    'research.unlocks': ['research'],
    'research.disables': ['research'],
    'research.getOneFree': ['research'],
    'research.getOneFreeProtected': ['research'],
    '/^research\\.getOneFreeProtected\\.[a-zA-Z0-9_]+$/': ['research'],
    'research.requires': ['research'],
    'research.requiresBaseFunc': ['facilities.provideBaseFunc'],
    'skills.requiredBonuses': ['soldierBonuses'],
    'soldiers.armor': ['armors'],
    'soldiers.requires': ['research'],
    'soldiers.skills': ['skills'],
    'soldiers.specialWeapon': ['items'],
    'soldierTransformation.soldierBonusType': ['soldierBonuses'],
    'startingBase.crafts[].type': ['crafts'],
    'startingBase.crafts[].weapons[].type': ['craftWeapons'],
    'startingBase.facilities[].type': ['facilities'],
    'startingBase.items': ['items'],
    'startingBase.randomSoldiers': ['soldiers'],
    'terrains.civilianTypes': ['units'],
    'terrains.enviroEffects': ['enviroEffects'],
    'terrains.mapBlocks[].items': ['items'],
    'terrains.mapBlocks[].randomizedItems[].itemList': ['items'],
    'terrains.script': ['mapScripts'],
    'ufos.raceBonus': ['alienRaces'],
    'units.armor': ['armors'],
    'units.builtInWeaponSets[]': ['items'],
    'units.psiWeapon': ['items'],
    'units.spawnUnit': ['units'],
    'startingConditions.defaultArmor': ['soldiers'],
    '/^startingConditions\\.defaultArmor\\.[a-zA-Z0-9_]+$/': ['armors'],
    'startingConditions.allowedArmors': ['armors'],
    'startingConditions.forbiddenArmors': ['armors'],
    'startingConditions.allowedVehicles': ['units'],
    'startingConditions.forbiddenVehicles': ['units'],
    'startingConditions.allowedItems': ['items'],
    'startingConditions.forbiddenItems': ['items'],
    'startingConditions.allowedItemCategories': ['itemCategories'],
    'startingConditions.forbiddenItemCategories': ['itemCategories'],
    'startingConditions.allowedCraft': ['crafts'],
    'startingConditions.forbiddenCraft': ['crafts'],
    'startingConditions.allowedSoldierTypes': ['soldiers'],
    'startingConditions.forbiddenSoldierTypes': ['soldiers'],
    'startingConditions.requiredItems': ['items'],
    //enviroEffects
    'manufacture.requires': ['research'],
    'manufacture.requiresBaseFunc': ['facilities.provideBaseFunc'],
    'manufacture.requiredItems': ['items'],
    'manufacture.producedItems': ['items'],
    'manufacture.randomProducedItems[][]': ['items'],
    'manufacture.spawnedPersonType': ['soldiers'], // also scientists and engineers
    'manufactureShortcut.startFrom': ['manufacture'],
    'manufactureShortcut.breakDownItems': ['manufacture'],
    // 'manufactureShortcut.breakDownRequires': ['research'],
    // 'manufactureShortcut.breakDownRequiresBaseFunc': ['facilities.provideBaseFunc'],
    'ufopaedia.requires': ['research'],
    'ufopaedia.weapon': ['items'],
    'alienMissions.spawnUfo': ['ufos'],
    'alienMissions.interruptResearch': ['research'],
    '/^alienMissions\\.raceWeights\\.\\d+$/': ['alienRaces'],
    'alienMissions.siteType': ['alienDeployments'],
    'alienMissions.operationBaseType': ['alienDeployments'],
    '/^alienMissions\\.regionWeights\\.\\d+$/': ['regions'],
    '/^missionScripts\\.missionWeights\\.\\d+$/': ['alienMissions'],
    '/^missionScripts\\.raceWeights\\.\\d+$/': ['alienRaces'],
    '/^missionScripts\\.regionWeights\\.\\d+$/': ['regions'],
    'missionScripts.researchTriggers': ['research'],
    'missionScripts.itemTriggers': ['items'],
    'missionScripts.facilityTriggers': ['facilities'],
    'arcScripts.sequentialArcs': ['research'],
    'arcScripts.randomArcs': ['research'],
    'arcScripts.researchTriggers': ['research'],
    'arcScripts.itemTriggers': ['items'],
    'arcScripts.facilityTriggers': ['facilities'],
    'eventScripts.oneTimeSequentialEvents': ['events'],
    'eventScripts.oneTimeRandomEvents': ['events'],
    '/^eventScripts\\.eventWeights\\.\\d+$/': ['events'],
    'eventScripts.researchTriggers': ['research'],
    'eventScripts.itemTriggers': ['items'],
    'eventScripts.facilityTriggers': ['facilities'],
    'events.regionList': ['regions'],
    'events.spawnedPersonType': ['soldiers'], // also scientists and engineers
    'events.everyItemList': ['items'],
    'events.everyMultiItemList': ['items'],
    'events.randomItemList': ['items'],
    'events.weightedItemList': ['items'],
    'events.researchList': ['research'],
    'events.interruptResearch': ['research'],
});
