#on: push
on:
  push:
    branches:
    - '*'
    tags-ignore:
    - 'v*-alpha*'

#  push:
#    branches:
#      - master

#env:
#  LOGLEVEL: 0 # debug

jobs:
  build:
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    -
      if: runner.os == 'Windows'
      run: yarn install
    -
      if: runner.os != 'Windows'
      run: npm install
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'
    - name: Archive code coverage results
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: coverage
  package:
    needs: build
    runs-on: ubuntu-latest
    # run if build is successful
    # if: steps.build.outcome == 'success'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: npm run vscode:prepublish
    - run: |
        pwd
        ls -Ral .
        ls -al out
    - name: Package
      run: npx vsce package
#      run: npx vsce package -o openxcom-ruleset-linker.vsix
    - name: Retrieve package
      uses: actions/upload-artifact@v2
      with:
        name: vscode-package
        path: '*.vsix'

