on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*-alpha*'
    - 'v*-rc*'

name: Upload Prerelease Asset

jobs:
  build:
    name: Upload Prerelease Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - name: Build & package project
        id: create_package
        run: |
          npx @vscode/vsce package --pre-release
          VSIX=$(echo *.vsix)
          echo "::set-output name=package_filename::$VSIX"
      - name: Create Prerelease
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Upload Prerelease Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./${{ steps.create_package.outputs.package_filename }}
          asset_name: ${{ steps.create_package.outputs.package_filename }}
          asset_content_type: application/zip
          # upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          # asset_path: ./my-artifact.zip
          # asset_name: my-artifact.zip
          # asset_content_type: application/zip